/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sic.Presentacion.Modulos.Subcontabilidad;

import java.awt.Color;
import javax.swing.JOptionPane;
import sic.Dominio.Core.EstructuraDeCostos.EstructuraDeCostos;
import sic.Dominio.Core.Subcontabilidad.Subcontabilidad;
import sic.Dominio.Core.Subcontabilidad.SubcontabilidadService;

/**
 *
 * @author Usuario1
 */
public class GestorDeSubcontabilidad extends javax.swing.JFrame implements sic.Presentacion.Suscripciones.ISuscripcion_BuscarSubcontabilidad,sic.Presentacion.Suscripciones.ISuscripcionBuscarEstructuraDeCostos{
    sic.Dominio.Core.Subcontabilidad.SubcontabilidadService service;
    sic.Presentacion.Modulos.Subcontabilidad.BuscarSubcontabilidad bs;
    Subcontabilidad subcontabilidad;
    Subcontabilidad subcontabilidad_padre;
    boolean buscar_padre=false;
    sic.Presentacion.Modulos.EstructuraDeCostos.BuscarEstructuraDeCostos bec;
    sic.Dominio.Core.EstructuraDeCostos.EstructuraDeCostos estructura_de_costos;
    /**
     * Creates new form GestorDeSubcontabilidad
     */
    public GestorDeSubcontabilidad() {
        initComponents();
        service=new sic.Dominio.Core.Subcontabilidad.SubcontabilidadService();
        this.getContentPane().setBackground(Color.WHITE);
        this.buscar_padre=true;
        this.setSubcontabilidad(null);
        this.setEstructuraDeCostos(null);
    }
    public void Buscar(){
        bs=new BuscarSubcontabilidad();
        bs.setSuscripcion(this);
        bs.show();
        this.dispose();
    }
    public void BuscarEstructuraDeCostos(){
        bec=new sic.Presentacion.Modulos.EstructuraDeCostos.BuscarEstructuraDeCostos();
        bec.setSuscripcion(this);
        bec.show();
        this.dispose();
    }
    public void Limpiar(){
        this.jFormattedTextField1.setValue(new Long(0));
        this.jTextField1.setText("");
        this.setSubcontabilidad(null);
        this.jButton1.setEnabled(true);
        this.jButton3.setEnabled(false);
        this.jButton4.setEnabled(true);
        this.setEstructuraDeCostos(null);
        this.buscar_padre=true;
        this.setSubcontabilidad(null);
        this.buscar_padre=false;
        
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestion de Subcontabilidades");

        jLabel2.setText("Codigo :");

        jFormattedTextField1.setEnabled(false);

        jLabel3.setText("Descripcion :");

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Modificar");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Limpiar");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel4.setText("Padre :");

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(255, 255, 255));

        jButton5.setText("Buscar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jFormattedTextField2.setEditable(false);
        jFormattedTextField2.setBackground(new java.awt.Color(255, 255, 255));

        jButton6.setText("Limpiar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel5.setText("Estructura De Costo :");

        jFormattedTextField3.setEditable(false);
        jFormattedTextField3.setBackground(new java.awt.Color(255, 255, 255));

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(255, 255, 255));

        jButton7.setText("Buscar");
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Limpiar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jFormattedTextField3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jFormattedTextField2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4))))
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7)
                    .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Subcontabilidad s=new Subcontabilidad();
        s.setDescripcion(this.jTextField1.getText());
        s.setPadre(this.subcontabilidad_padre);
        s.setEstructura_de_costos(estructura_de_costos);
        service.getDao().Persistir(s);
        JOptionPane.showMessageDialog(this,"Guardado con exito");
        this.Limpiar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.buscar_padre=false;
        this.Buscar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:        
        this.subcontabilidad.setDescripcion(this.jTextField1.getText());        
        this.subcontabilidad.setPadre(this.subcontabilidad_padre);
        this.subcontabilidad.setEstructura_de_costos(estructura_de_costos);
        service.getDao().Modificar(subcontabilidad);
        JOptionPane.showMessageDialog(this,"Modificado Con Exito");
        this.Limpiar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.Limpiar();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.buscar_padre=true;
        this.Buscar();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.subcontabilidad_padre=null;
        this.buscar_padre=true;
        this.setSubcontabilidad(subcontabilidad_padre);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
           this.BuscarEstructuraDeCostos();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestorDeSubcontabilidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

    @Override
    public void EventoDeSeleccionDeSubcontabilidad() {
        if(this.buscar_padre==false){           
           this.show();
           this.bs.dispose();
           this.jButton1.setEnabled(false);
           this.jButton3.setEnabled(true);
           this.jButton4.setEnabled(true);        
           this.setSubcontabilidad(bs.getSeleccionado());                      
           this.jButton7.setEnabled(true);
        }else{
           if(service.isEsteril(bs.getSeleccionado().getId())==false){
              this.show();
              this.bs.dispose();
              this.setSubcontabilidad(bs.getSeleccionado());              
            }else{
               JOptionPane.showMessageDialog(this.bs,"ESTA SUBCONTABILIDAD ES ESTERIL");
            }
        }
    }

    @Override
    public void setSubcontabilidad(Subcontabilidad subcontabilidad) {           
        if(subcontabilidad!=null){
           if(this.buscar_padre==false) {
              this.subcontabilidad=subcontabilidad;
              this.jFormattedTextField1.setValue(new Long(subcontabilidad.getId()));
              this.jTextField1.setText(subcontabilidad.getDescripcion());
              this.subcontabilidad_padre=subcontabilidad.getPadre();
              this.setEstructuraDeCostos(subcontabilidad.getEstructura_de_costos());
              if(this.subcontabilidad_padre!=null){
                 SubcontabilidadService ss=new SubcontabilidadService();
                 Subcontabilidad s=ss.getDao().Obtener(subcontabilidad_padre.getId());
                 this.jFormattedTextField2.setValue(new Long(s.getId()));
                 this.jTextField3.setText(s.getDescripcion());
              }else{
                 this.jFormattedTextField2.setValue(new Long(0));
                 this.jTextField3.setText("Ninguno");
              }
           }else{
              this.subcontabilidad_padre=subcontabilidad;
              this.jFormattedTextField2.setValue(new Long(subcontabilidad.getId()));
              this.jTextField3.setText(subcontabilidad.getDescripcion());
           }
        }else{
           if(this.buscar_padre==false){ 
              this.jFormattedTextField1.setValue(new Long(0));
              this.jFormattedTextField1.setEnabled(false);
              this.jTextField1.setText("");              
           }else{
              this.jFormattedTextField2.setValue(new Long(0));
              this.jTextField3.setText("Ninguno");
           }
        }
    }

    @Override
    public void EventoDeSeleccionEstructuraDeCostos() {
         if(service.getDao().ObtenerHijos(subcontabilidad.getId()).isEmpty()){
             this.setEstructuraDeCostos(bec.getSeleccionado());
             this.bec.dispose();
             this.show();             
         }else{
             JOptionPane.showMessageDialog(this.bec,"SOLO LOS NODO HOJAS PUEDEN ESCOJER ESTRUCTURAS DE COSTOS");
         }
    }

    @Override
    public void setEstructuraDeCostos(EstructuraDeCostos obj) {
       this.estructura_de_costos=obj;
       if(obj!=null){
           this.jFormattedTextField3.setValue(new Long(obj.getId()));
           this.jTextField4.setText(""+obj.getDescripcion());
       }else{
           this.jFormattedTextField3.setValue(new Long(0));
           this.jTextField4.setText("Ninguna");
       }
    }
}
