/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BuscarEnAuxiliar.java
 *
 * Created on 4/04/2012, 11:28:02 PM
 */
package sic.Presentacion.Modulos.PUC;

import java.awt.Color;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JViewport;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import sic.Dominio.Core.Cta_T.Cta_T;
import sic.Dominio.Core.PUC.Cta_PUC;
import sic.Dominio.Core.PUC.PucService;
import sic.Presentacion.ModelosDeTabla.Cta_PUCModel;
import sic.Presentacion.Suscripciones.ISuscripcionBuscarEnAuxiliar;

/**
 *
 * @author FANNY BURGOS
 */
public class BuscarEnAuxiliar extends javax.swing.JFrame implements sic.Presentacion.Suscripciones.ISuscripcionBuscarEnPUC{
    BuscarEnPUC bp;
    Cta_PUC ctapuc=null;
    Cta_PUC ctaauxiliar=null;
    Cta_PUCModel m;
    PucService service;
    int filaSeleccionada=-1;
    private ISuscripcionBuscarEnAuxiliar suscripcion=null;
    private Cta_T ctat=null;
    /** Creates new form BuscarEnAuxiliar */
    public BuscarEnAuxiliar() {
        initComponents();        
        service =new PucService();
        this.SeleccionarCtaEnPUC();        
        m=new Cta_PUCModel();
        this.jTable1.setModel(m);
        this.setAnchoColumnas();
        this.jTextField1.requestFocus();
        this.getContentPane().setBackground(Color.WHITE);
    }
    void Buscar(){
        String busqueda=this.jTextField1.getText();
        m=new Cta_PUCModel();        
        if(ctapuc!=null){        
           m.setLista(service.InspeccionarAuxiliar(busqueda,this.ctapuc.getId()));        
        }
        this.jTable1.setModel(m);                
        this.setAnchoColumnas();
    }
    void Seleccionar(){
        if(this.filaSeleccionada!=-1){
           this.ctaauxiliar=m.getRow(this.filaSeleccionada);
           if(this.suscripcion!=null)
           this.suscripcion.EventoDeSeleccionAuxiliar();
        }else{
            JOptionPane.showMessageDialog(this,"debes escoger una fila");
        }
    }
    void SeleccionarCtaEnPUC(){        
        bp=new BuscarEnPUC();
        bp.show();
        bp.setSuscripcion(this);
        this.dispose();    
        this.jTextField1.requestFocus();
        this.Buscar();
    }
    public Cta_PUC ObtenerAuxiliarSeleccionado(){
        return this.ctaauxiliar;
    }
    void IngresarEnAuxiliar(){
        System.out.println(ctat.getDescripcion()+" "+ctat.getId());
        this.service.IngresarEnElPUC(this.ctapuc.getId()+""+ctat.getId(),ctat.getDescripcion(),this.ctapuc.getTipoCta(),this.ctapuc.isRequiereNit(),ctat,ctapuc.isPublico(),ctapuc.getCategoria());        
        this.jButton2.setEnabled(false);
        this.Buscar();      
        if(this.suscripcion!=null){
            this.InicializarCtaAuxiliar();
            this.suscripcion.EventoDeSeleccionAuxiliar();
        }
    }
    void InicializarCtaAuxiliar(){
        ctaauxiliar=new  Cta_PUC();
            this.ctaauxiliar.setId(this.ctapuc.getId()+""+ctat.getId());
            this.ctaauxiliar.setCtat(ctat);
            this.ctaauxiliar.setDenominacion(ctat.getDescripcion());
            this.ctaauxiliar.setTipoCta(this.ctapuc.getTipoCta());
            this.ctaauxiliar.setRequiereNit(this.ctapuc.isRequiereNit());            
    }
    public void setAnchoColumnas(){       
        JViewport scroll =  (JViewport) this.jTable1.getParent();
        int ancho = scroll.getWidth();
        int anchoColumna=0;
        TableColumnModel modeloColumna = this.jTable1.getColumnModel();
        TableColumn columnaTabla;
        for (int i = 0; i < this.jTable1.getColumnCount(); i++) {
            columnaTabla = modeloColumna.getColumn(i);
            switch(i){
                case 0: anchoColumna = (15*ancho)/100;
                        break;
                 case 1: anchoColumna = (60*ancho)/100;
                        break;       
                case 2: anchoColumna = (15*ancho)/100;
                        break;           
                case 3: anchoColumna = (10*ancho)/100;
                        break;              
            }                     
            columnaTabla.setPreferredWidth(anchoColumna);           
        }
    }  
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sic/Presentacion/Modulos/PUC/image (20).png"))); // NOI18N

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton1.setText("Seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"11050501", "Ciro Cayo De Leon Burgos - 10784054"}
            },
            new String [] {
                "Cod. Aux", "Descripcion"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton2.setText("Ingresar");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jMenu1.setText("Opciones");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem1.setText("Ingresar");
        jMenuItem1.setEnabled(false);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        jMenuItem2.setText("Seleccionar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if(this.jTable1.getSelectedRow()!=-1){
            this.filaSeleccionada=this.jTable1.getSelectedRow();            
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        this.Buscar();
        if(evt.getKeyCode()==evt.VK_DOWN){
            this.jTable1.requestFocus();
            this.jTable1.changeSelection(0,0,false,false);
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.Seleccionar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.IngresarEnAuxiliar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==evt.VK_ENTER){
            if(this.jTable1.getSelectedRow()!=-1){
                this.filaSeleccionada=this.jTable1.getSelectedRow();
                this.Seleccionar();
            }else{
                JOptionPane.showMessageDialog(this,"Debe Seleccionar una Fila");
            }
        }
    }//GEN-LAST:event_jTable1KeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if(this.suscripcion!=null){
            this.suscripcion.show();
            this.dispose();
        }else{
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.IngresarEnAuxiliar();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.Seleccionar();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new BuscarEnAuxiliar().setVisible(false);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void EventoDeSeleccionCtaEnPUC() {        
            if(this.bp.ObtenerCtaSeleccionada().getId().toString().length()==8){
                this.ctapuc=bp.ObtenerCtaSeleccionada();
                this.setTitle(ctapuc.getId()+"==>"+ctapuc.getDenominacion());
                this.bp.dispose();              
                
                if(ctat!=null && this.service.ObtenerCtaPuc(ctapuc.getId()+""+ctat.getId())!=null){
                    this.jButton2.setEnabled(false);
                    this.jMenuItem1.setEnabled(false);
                    this.InicializarCtaAuxiliar();
                    this.suscripcion.EventoDeSeleccionAuxiliar();
                }else{
                    this.show();    
                    this.jTextField1.setText("");
                    if(this.ctapuc.isPublico()==false){
                        this.jButton2.setEnabled(false);
                        this.jMenuItem1.setEnabled(false);
                    }
                }
                
                this.Buscar();
            }else{
                JOptionPane.showMessageDialog(this.bp,"Debe Ser Un  Aux. Contable");
            }            
    }

    @Override
    public void setCta_PUC(Cta_PUC cta) {
        this.ctapuc=cta;
    }

    /**
     * @param suscripcion the suscripcion to set
     */
    public void setSuscripcion(ISuscripcionBuscarEnAuxiliar suscripcion) {
        this.suscripcion = suscripcion;
    }

    /**
     * @param ctat the ctat to set
     */
    public void setCtat(Cta_T ctat) {
        if(ctat!=null){
           this.ctat = ctat;          
           this.jButton2.setToolTipText(ctat.getDescripcion());
           this.jButton2.setEnabled(true);
        }else{
            this.ctat=null;
        }
        
    }
}
